files:
    model: ./converted_R-HSA-1643713.sbml
    parameters: ./parameters.tsv
    constrains: ./constrains.tsv
    objective: ./objective.tsv
    valori: ./vals.tsv
horizon: 10000
absolute_tolerance: 1.0e-18
relative_tolerance: 1.0e-12
time_step: 10

loss_functions:
    stability:
        scale: 10000
    transitorial:
        scale: 10
    value:
        scale: 1

simulator: RoadRunner
#solver: NOMAD
random_seed: 3456789
#solver_parameters:
#    - SEED 104
#    - MAX_ITERATIONS 1700
#    - NB_THREADS_PARALLEL_EVAL 1
#    - MAX_EVAL 1700
solver: openai 
solver_parameters:
    episodes: 500
    population: 125
    seed: 3456789
    learning_rate: 1e-10

#solver: nevergrad
#solver_parameters:
#    optimizer: NGOpt
#    budget: 300 
#    seed: 104