files:
    model: ./converted_R-HSA-390471.sbml
    parameters: ./parameters.tsv
    objective: ./objective.tsv
    # ordinamento: ./ord.tsv
    valori: ./vals.tsv
horizon: 5000
absolute_tolerance: 1.0e-12
relative_tolerance: 1.0e-06
time_step: 0.5

loss_functions:
    stability:
        scale: 10000
    transitorial:
         scale: 10
    #fitting:
    #    scale: 10
    value:
        scale: 1

random_seed: 104 
simulator: RoadRunner

#solver: NOMAD
#solver_parameters:
#    - SEED 104
#    - MAX_ITERATIONS 100000
#    - NB_THREADS_PARALLEL_EVAL 1
#    - MAX_EVAL 150000

#solver: nevergrad
#solver_parameters:
#    optimizer: DE
#    budget: 100000
#    seed: 104

solver: openai 
solver_parameters:
    episodes: 10000
    population: 200
    seed: 104
    learning_rate: 5e-9
    global_minimum: 0.0