files:
    model: ./converted_R-HSA-169911.sbml
    parameters: ./parameters.tsv
    objective: ./objective.tsv
    constrains: ./constrains.tsv
    # ordinamento: ./ord.tsv
    valori: ./vals.tsv
horizon: 10000
absolute_tolerance: 1.0e-12
relative_tolerance: 1.0e-06
time_step: 10

loss_functions:
    stability:
        scale: 10000
    transitorial:
        scale: 10
    value:
        scale: 1

simulator: RoadRunner
#random_seed: 9827359
random_seed: 104 
solver: NOMAD
solver_parameters:
    - SEED 104
    - MAX_ITERATIONS 100000
    - NB_THREADS_PARALLEL_EVAL 1
    - MAX_EVAL 1500000
#solver: nevergrad
#solver_parameters:
#    optimizer: NGOpt
#    budget: 1000
#    seed: 104

#solver: openai 
#solver_parameters:
#    episodes: 50
#    population: 100
#    seed: 104
#    learning_rate: 0.01